### ISSUE TITLE
Failed to resolve: me.tylerbwong.allaboard:1.0.1:

### ISSUE THREAD

**Issue by rlee1990** [tylerbwong/AllAboard#1]
Cannot compile the file. Receives an error: Failed to resolve: me.tylerbwong.allaboard:1.0.1:

**Comment by tylerbwong** [comment]
Hey @rlee1990, thanks for letting me know! There was a typo in the README, but I've updated the setup instructions. You should use `implementation me.tylerbwong:allaboard:1.0.2` instead.

Let me know if that works for you.

**Comment by rlee1990** [comment]
That worked
