### ISSUE TITLE
Custom navigation buttons and click handlers?

### ISSUE THREAD

**Issue by arthabus** [tylerbwong/AllAboard#2]
Hey, great lib - thanks for sharing it with the community!

I have a question - is it possible to customize the back/forward buttons? Or maybe to remove them and switch the pages programmatically?

My requirement is to have "skip" button with text instead of back one  and "next" instead of the arrow that changes to "finish" if it's the last step.

Is it possible to achieve this easily with the library in some way?

Thanks again!

**Comment by tylerbwong** [comment]
Hey @arthabus thanks for taking a look!

I've added some changes in #3. Feel free to review and let me know what you think about the new additions to the API.

Thanks a lot!

**Comment by arthabus** [comment]
hey @tylerbwong - thanks a lot for quick reply and extending the API! Looks like exactly what I was looking for!

Thanks again!

**Comment by tylerbwong** [comment]
Awesome, I'll cut a new release later tonight.

**Comment by tylerbwong** [comment]
Released in [1.1.0](https://bintray.com/tylerbwong/maven/AllAboard/1.1.0)!
